### ISSUE TITLE
Previously reliably importable models now not importing

### ISSUE THREAD

**Issue by bigmikemw** [riverence/io_scene_binfbx#1]
Previously reliably importable models now not importing after the latest commit

Here's the error message:

```
Python: Traceback (most recent call last):
  File "C:\Users\misak\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_binfbx\__init__.py", line 1060, in main
    boneid = wgt[vrt][0]
IndexError: list index out of range
```
Script usually loads one (LOD3) mesh per model with this error, disabling the "Import rig" option results in full LOD3 models being imported, with Estevez it's LOD5 
![image](https://github.com/riverence/io_scene_binfbx/assets/161866844/6a5bb172-9afc-48ae-9ae1-88b385eda857)

**Comment by riverence** [comment]
This is due to me being in the process of implementing an automatic method for finding the offsets; currently, the addon can only reliably find the highest LOD offset. However, there's some strange issues with the weights that I need to sort out, and I also need to actually get it to read all the LODs. For now, it's recommended you use the version of the addon from [this commit](https://github.com/riverence/io_scene_binfbx/tree/184733963f7c24712b81ee263078d9de1bd14b24), or use the newest stable version, 2.0.0, under the Releases tab. In the future, I'll add a testing branch to keep an up-to-date and confirmed working version and a heavy-development version distinct.
